- name: Run using a project directory
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: mqtt-docker
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        
        project_src: mqtt-docker
        state: present
      register: output

    - ansible.builtin.debug:
        var: output
