---
#
# creat mosquitto container
#
- name: create a container based on the official mosquitto image
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Create the mosquitto container
      community.docker.docker_container:
        name: mosquitto-container
        image: eclipse-mosquitto
        volumes:
          - ./mosquitto-docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
        working_dir: /mosquitto
        ports:
          - "1883:1883"
          - "9001:9001"
        state: present
      register: output

    - ansible.builtin.debug:
        var: output
...